# -*- coding: utf-8 -*-
"""schedule.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mx3BKO-v_lqSRy_UwIhZYxOxAOQK-bGD
"""

!pip install schedule
!pip install pymongo

import schedule
import time
from google.colab import drive

def run_etl():
    print("Running daily ETL job...")
    drive.mount('/content/drive')
    exec(open("/content/drive/MyDrive/ETL_Pipeline_ArsalanAli_DS-054_2024/etl_pipeline.py").read())

# Schedule job
schedule.every().day.at("08:00").do(run_etl)
while True:
    schedule.run_pending()
    time.sleep(60)